# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvQFaUO2gscGz4wbpMUcI1kkw4qT7OSv
"""

import numpy as np

A = np.array([[0, 2, 4, 6], [1, 3, 5, 7]])  # shape: (2, 4)
B = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])  # shape: (4, 2)

result = np.dot(A, B)
print(result)
print(result.max())  # 最大値を表示